spring:
  flyway:
    schemas: todolist_test
    create-schemas: true
    url: jdbc:h2:mem:todolist_test

  datasource:
    url: jdbc:h2:mem:todolist_test;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
